### ISSUE TITLE
Bad encoding

### ISSUE THREAD

**Issue by emakei** [sergot/perl6-encode#15]
Maybe just i'm doing something wrong but then what?
![171335772-22f1eba3-facc-44bb-816d-5528324005e9 1](https://user-images.githubusercontent.com/8183849/171615937-531ef4bd-250c-4353-957c-521e4a911eef.png)

**Comment by sergot** [comment]
Is this the first time this occurred or did you experience it before?

I've merged some PRs recently.

**Comment by emakei** [comment]
> Is this the first time this occurred or did you experience it before?
> 
> I've merged some PRs recently.

First time. This version bundled I guess with Star bundle. Version 0.0.2

**Comment by Demayl** [comment]
Here is a example how to use the module
```raku
my Buf $str = Buf.new( 0xFF, 0xFE ); # яю

say Encode::decode("windows1251", $str);
```

**Comment by emakei** [comment]
Works correct when starting cmd in 65001 encoding
